name: Deploy to pkg branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write
    name: Deploy to pkg branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pkg
          FOLDER: pkg
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}